# Generated by Django 5.0.1 on 2024-05-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractucture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temp', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
    ]
