# Generated by Django 5.0.1 on 2024-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractucture', '0002_weather_delete_accounts_delete_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='model_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
